version: '2.3'

services:
    ur_robot:
        image: ragesh18/ur5e_cell:main
        container_name: ur5e_cell
        platform: linux/amd64
        restart: always
        pull_policy: always
        # Uncomment this for development
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        network_mode: "host"
        ipc: host
        environment:
            - ROS_DOMAIN_ID=2
            - DISPLAY
        volumes: 
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        command: ros2 launch ur5e_cell_moveit_config robot.launch.py